### ISSUE TITLE
Can't run tests locally

### ISSUE THREAD

**Issue by onigoetz** [bluelovers/ws-iconv#3]
Hi, I'm trying to make a PR to this project but I can't seem to run the tests locally.

I don't understand how the project is compiled as there is no dependency to Typescript or Jest configuration.

What am I missing ?
Thanks in advance

**Comment by bluelovers** [comment]
- ts-node
- typescript
- jest
- ts-jest

**Comment by onigoetz** [comment]
Okay, but shouldn't they be added as dependencies to the project or the workspace for CI and reproducibility?

**Comment by bluelovers** [comment]
> Okay, but shouldn't they be added as dependencies to the project or the workspace for CI and reproducibility?

i want avoid install that in my every local projects, so i didn't add it into deps

**Comment by onigoetz** [comment]
Aren't yarn's local cache and devDependencies here for that ?

**Comment by bluelovers** [comment]
some test only work run on windows
if u wanna make pr, u can just test ur part, didn't need make all test work, i will check it before merge

**Comment by onigoetz** [comment]
okay thanks for the info
