### ISSUE TITLE
Does `upath2` really needs `@types/node` as peer dependency?

### ISSUE THREAD

**Issue by felipecrs** [bluelovers/ws-iconv#5]
This issues warnings on libraries depending on it, but which does not have `@types/node` added directly.

Example:

```log
[3/4] Linking dependencies...
warning "rollup-plugin-typescript2 > @yarn-tool/resolve-package > upath2@3.1.12" has unmet peer dependency "@types/node@*".
```

**Comment by felipecrs** [comment]
@bluelovers, any chance you can publish a new version with the fix? I don't want to rush anything, but maybe you forgot. :)

**Comment by felipecrs** [comment]
But no newer versions of upath2 were released after https://github.com/bluelovers/ws-iconv/commit/20b611fbd590f382c4d2f9be7f242a55d1887624.

**Comment by bluelovers** [comment]
oops, should be ok now

**Comment by felipecrs** [comment]
Thanks a lot! :)
